"""
round2_process.py — Filter, assign competitors, and merge round 2 data with round 1.

Pipeline:
1. Load round2_raw_apify.json
2. Dedup + apply ICP filter (same rules as 02_filter_icp.py)
3. Assign competitors against ROUND 2 pool only (round 1 spas are too far away anyway)
4. Append new primaries to existing master-list.csv (dedup by gbp_url)
5. Re-run merge_to_all_leads.py to produce updated unified all-leads.csv

Outputs:
- data/round2_primaries.json — round 2 ICP-fit + competitors
- leads/master-list.csv — extended with round 2 (round 1 rows preserved)
- leads/competitors.csv — extended with round 2 competitor rows
- leads/all-leads.csv — regenerated by re-running merge_to_all_leads

Run:
    python3 round2_process.py
"""

import csv
import json
import math
import os
import re
import subprocess
import sys
from collections import OrderedDict
from typing import Dict, List, Optional, Tuple

from config import (
    CHAIN_BLOCKLIST,
    KEEP_CATEGORIES,
    DROP_CATEGORIES,
    MIN_REVIEW_COUNT,
    MIN_STAR_RATING,
    COMPETITOR_RADIUS_MILES,
    COMPETITORS_PER_PRIMARY,
    DATA_DIR,
    MASTER_CSV,
    COMPETITORS_CSV,
)

ROUND2_RAW_JSON = os.path.join(DATA_DIR, "round2_raw_apify.json")
ROUND2_PROCESSED_JSON = os.path.join(DATA_DIR, "round2_primaries.json")


# -- Filter helpers (mirrors 02_filter_icp.py) -------------------------------

def normalize_name(name): return (name or "").lower().strip()

def is_chain(place):
    name = normalize_name(place.get("title", ""))
    return any(chain in name for chain in CHAIN_BLOCKLIST)

def has_dropped_category(place):
    cats = [normalize_name(c) for c in place.get("categories", [])]
    cats.append(normalize_name(place.get("categoryName", "")))
    return any(d in cat for cat in cats for d in DROP_CATEGORIES)

def has_kept_category(place):
    cats = [normalize_name(c) for c in place.get("categories", [])]
    cats.append(normalize_name(place.get("categoryName", "")))
    return any(k in cat for cat in cats for k in KEEP_CATEGORIES)

def passes_review_floor(place):
    count = place.get("reviewsCount") or 0
    rating = place.get("totalScore") or 0
    return count >= MIN_REVIEW_COUNT and rating >= MIN_STAR_RATING


# -- Distance helper (mirrors 03_assign_competitors.py) ----------------------

def haversine_miles(lat1, lng1, lat2, lng2):
    R = 3959
    phi1, phi2 = math.radians(lat1), math.radians(lat2)
    dphi = math.radians(lat2 - lat1)
    dlambda = math.radians(lng2 - lng1)
    a = math.sin(dphi/2)**2 + math.cos(phi1)*math.cos(phi2)*math.sin(dlambda/2)**2
    return 2 * R * math.asin(math.sqrt(a))

def get_lat_lng(place):
    loc = place.get("location") or {}
    lat = loc.get("lat") or place.get("lat")
    lng = loc.get("lng") or place.get("lng") or place.get("lon")
    if lat is None or lng is None:
        return None
    return float(lat), float(lng)


# -- Process ----------------------------------------------------------------

def filter_round2(raw):
    seen = set()
    deduped = []
    for place in raw:
        cid = place.get("placeId") or place.get("url", "")
        if cid and cid not in seen:
            seen.add(cid)
            deduped.append(place)
    print(f"  Deduped: {len(deduped)} unique places", file=sys.stderr)

    primaries = []
    pool = []
    dropped = {"chain": 0, "category": 0, "low_reviews": 0, "no_categories": 0}

    for place in deduped:
        if has_dropped_category(place):
            dropped["category"] += 1
            continue
        if not has_kept_category(place):
            dropped["no_categories"] += 1
            continue
        if is_chain(place):
            pool.append(place)
            dropped["chain"] += 1
            continue
        if not passes_review_floor(place):
            pool.append(place)
            dropped["low_reviews"] += 1
            continue
        primaries.append(place)
        pool.append(place)

    print(f"  Primary targets: {len(primaries)}", file=sys.stderr)
    print(f"  Competitor pool: {len(pool)}", file=sys.stderr)
    print(f"  Dropped: {dropped}", file=sys.stderr)
    return primaries, pool


def assign_competitors(primaries, pool):
    enriched = []
    for primary in primaries:
        p_loc = get_lat_lng(primary)
        if p_loc is None:
            primary["_competitors"] = []
            enriched.append(primary)
            continue

        primary_id = primary.get("placeId") or primary.get("url")
        candidates = []
        for other in pool:
            if other is primary: continue
            if (other.get("placeId") or other.get("url")) == primary_id: continue
            o_loc = get_lat_lng(other)
            if o_loc is None: continue
            dist = haversine_miles(p_loc[0], p_loc[1], o_loc[0], o_loc[1])
            if dist > COMPETITOR_RADIUS_MILES: continue
            candidates.append((dist, other))

        candidates.sort(key=lambda x: (x[0], -(x[1].get("reviewsCount") or 0)))
        closest = candidates[:COMPETITORS_PER_PRIMARY * 2]
        closest.sort(key=lambda x: -(x[1].get("reviewsCount") or 0))

        primary["_competitors"] = [
            {
                "name": c["title"],
                "review_count": c.get("reviewsCount") or 0,
                "star_rating": c.get("totalScore") or 0,
                "distance_miles": round(d, 2),
                "gbp_url": c.get("url"),
                "address": c.get("address"),
            }
            for d, c in closest[:COMPETITORS_PER_PRIMARY]
        ]
        enriched.append(primary)
    return enriched


# -- Append to master CSV -----------------------------------------------------

def parse_city_state_zip(place):
    city = (place.get("city") or "").strip()
    state = (place.get("state") or "").strip()
    zip_code = (place.get("postalCode") or place.get("zip") or "").strip()
    if city and state:
        return city, state, zip_code
    address = (place.get("address") or "").strip()
    m = re.search(r",\s*([^,]+),\s*([A-Z]{2})\s+(\d{5})", address)
    if m:
        return m.group(1).strip(), m.group(2), m.group(3)
    return city, state, zip_code


def extract_instagram(place):
    igs = place.get("instagrams") or place.get("socialProfiles", {}).get("instagram")
    if igs:
        if isinstance(igs, list): return igs[0]
        if isinstance(igs, str): return igs
    return ""


def safe_str(v): return str(v).strip() if v else ""
def safe_int(v):
    try: return int(v) if v else 0
    except: return 0
def safe_float(v):
    try: return float(v) if v else 0.0
    except: return 0.0


MASTER_HEADERS = [
    "name", "city", "state", "zip", "phone", "website", "instagram",
    "email", "email_source", "google_review_count", "google_star_rating",
    "address", "gbp_url", "categories",
    "top_competitor_1_name", "top_competitor_1_reviews", "top_competitor_1_stars", "top_competitor_1_distance",
    "top_competitor_2_name", "top_competitor_2_reviews", "top_competitor_2_stars", "top_competitor_2_distance",
    "top_competitor_3_name", "top_competitor_3_reviews", "top_competitor_3_stars", "top_competitor_3_distance",
    "notes", "call_status", "call_attempts", "last_attempted",
]


def primary_to_row(place):
    city, state, zip_code = parse_city_state_zip(place)
    comps = place.get("_competitors") or []
    row = {
        "name": safe_str(place.get("title")),
        "city": city,
        "state": state,
        "zip": zip_code,
        "phone": safe_str(place.get("phone") or place.get("phoneNumber")),
        "website": safe_str(place.get("website")),
        "instagram": safe_str(extract_instagram(place)),
        "email": "",
        "email_source": "",
        "google_review_count": safe_int(place.get("reviewsCount")),
        "google_star_rating": safe_float(place.get("totalScore")),
        "address": safe_str(place.get("address")),
        "gbp_url": safe_str(place.get("url")),
        "categories": "; ".join(place.get("categories") or []),
        "notes": "",
        "call_status": "not_called",
        "call_attempts": 0,
        "last_attempted": "",
    }
    for i in range(3):
        c = comps[i] if i < len(comps) else {}
        row[f"top_competitor_{i+1}_name"] = safe_str(c.get("name"))
        row[f"top_competitor_{i+1}_reviews"] = safe_int(c.get("review_count"))
        row[f"top_competitor_{i+1}_stars"] = safe_float(c.get("star_rating"))
        row[f"top_competitor_{i+1}_distance"] = safe_float(c.get("distance_miles"))
    return row


def comp_rows(primaries):
    rows = []
    for place in primaries:
        primary_name = safe_str(place.get("title"))
        city, _, _ = parse_city_state_zip(place)
        for rank, c in enumerate(place.get("_competitors") or [], start=1):
            rows.append({
                "primary_spa_name": primary_name,
                "primary_spa_city": city,
                "competitor_rank": rank,
                "competitor_name": safe_str(c.get("name")),
                "competitor_review_count": safe_int(c.get("review_count")),
                "competitor_star_rating": safe_float(c.get("star_rating")),
                "competitor_distance_miles": safe_float(c.get("distance_miles")),
                "competitor_gbp_url": safe_str(c.get("gbp_url")),
            })
    return rows


def append_to_master(new_primaries):
    """Append new rows to existing master-list.csv, dedup by gbp_url."""
    existing_urls = set()
    existing_rows = []
    if os.path.exists(MASTER_CSV):
        with open(MASTER_CSV) as f:
            for row in csv.DictReader(f):
                existing_urls.add(row.get("gbp_url", ""))
                existing_rows.append(row)

    new_rows = []
    for p in new_primaries:
        row = primary_to_row(p)
        if row["gbp_url"] in existing_urls:
            continue
        new_rows.append(row)

    all_rows = existing_rows + new_rows
    with open(MASTER_CSV, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=MASTER_HEADERS, quoting=csv.QUOTE_ALL)
        writer.writeheader()
        for r in all_rows:
            writer.writerow({h: r.get(h, "") for h in MASTER_HEADERS})
    print(f"Master CSV: {len(existing_rows)} existing + {len(new_rows)} new = {len(all_rows)} total", file=sys.stderr)
    return len(new_rows)


def append_to_competitors(new_primaries):
    new_comp_rows = comp_rows(new_primaries)
    fieldnames = [
        "primary_spa_name", "primary_spa_city", "competitor_rank",
        "competitor_name", "competitor_review_count", "competitor_star_rating",
        "competitor_distance_miles", "competitor_gbp_url",
    ]
    existing = []
    if os.path.exists(COMPETITORS_CSV):
        with open(COMPETITORS_CSV) as f:
            existing = list(csv.DictReader(f))

    all_rows = existing + new_comp_rows
    with open(COMPETITORS_CSV, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, quoting=csv.QUOTE_ALL)
        writer.writeheader()
        for r in all_rows:
            writer.writerow({k: r.get(k, "") for k in fieldnames})
    print(f"Competitors CSV: {len(existing)} existing + {len(new_comp_rows)} new = {len(all_rows)} total", file=sys.stderr)


# -- Main -------------------------------------------------------------------

def main():
    if not os.path.exists(ROUND2_RAW_JSON):
        print(f"ERROR: {ROUND2_RAW_JSON} not found. Run round2_scrape.py first.", file=sys.stderr)
        sys.exit(1)

    print(f"Loading round 2 raw data...", file=sys.stderr)
    with open(ROUND2_RAW_JSON) as f:
        raw = json.load(f)
    print(f"  {len(raw)} raw items", file=sys.stderr)

    print(f"\nFiltering ICP...", file=sys.stderr)
    primaries, pool = filter_round2(raw)

    print(f"\nAssigning competitors (round 2 pool only)...", file=sys.stderr)
    enriched = assign_competitors(primaries, pool)
    print(f"  Enriched {len(enriched)} primaries", file=sys.stderr)

    with open(ROUND2_PROCESSED_JSON, "w") as f:
        json.dump(enriched, f, indent=2)

    print(f"\nAppending to master CSVs...", file=sys.stderr)
    new_count = append_to_master(enriched)
    append_to_competitors(enriched)

    print(f"\nRegenerating all-leads.csv via merge script...", file=sys.stderr)
    result = subprocess.run(
        ["python3", os.path.join(os.path.dirname(os.path.abspath(__file__)), "merge_to_all_leads.py")],
        capture_output=True, text=True,
    )
    print(result.stderr, file=sys.stderr)

    print(f"\n✓ Round 2 complete. Added {new_count} new primaries.", file=sys.stderr)


if __name__ == "__main__":
    main()
